[project]
name = "exchangetracker"
version = "0.0.3"
description = "Збір і аналіз курсу валют та металів"
requires-python = ">=3.12"
dependencies = [
    "requests==2.31.0",
    "yfinance==1.7.0",
    "tabulate==0.10.0"
]

[project.optional-dependencies]
dev = ["ruff", "pytest", "pre-commit", "mypy", "types-requests", "types-tabulate", "pydantic", "pydantic-settings"]

[project.scripts]
exchangetracker = "exchangetracker.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.mypy]
python_version = "3.12"
show_error_codes = true
warn_unused_ignores = true
strict=true

[[tool.mypy.overrides]]
module = ["some_untyped_lib.*"]
ignore_missing_imports = true
